### ISSUE TITLE
philips.light.zysread

### ISSUE THREAD

**Issue by and217** [syssi/philipslight#15]
https://youpin.mi.com/detail?gid=101802

**Comment by syssi** [comment]
It looks like the device is similar to the Eyecare 2 lamp. You could try the configuration for testing:

```
light:
 - platform: xiaomi_miio
    name: Philips Light Zysread
    host: <your-device-ip>
    token: <your-device-token>
    model: philips.light.sread1
```

If the device behaves like a "sread1" I will extend the component.
