### ISSUE TITLE
Missing Device record in Devices list

### ISSUE THREAD

**Issue by cranetm** [syssi/philipslight#63]
Hello,
I'm trying to add philips zhirui downlights. 
I've got new entity light.lights1. The issue is  - there is no Device in Devices & Services -> Devices list.
_Also, I've noticed, that if I put a `model` explicitly, `unique_id` is empty and in some cases, HA gives me an error "This entity does not have a unique ID, therefore its settings cannot be managed from the UI". So, I removed `model` from config and integration does the job with `unique_id`._

But still, no Device.

My configuration:
```
light:
  - platform: xiaomi_miio_philipslight
    name: lights1
    host: 192.168.0.6
    token: ....
```
